---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached-store
  template:
    metadata:
      labels:
        app: memcached-store
    spec:
      containers:
        - name: memcached-store
          image: memcached
          ports:
            - containerPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  name: memcached-store
spec:
  selector:
    app: memcached-store
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211